name: Onboarding Checklist Issue

on:
  workflow_dispatch:
    inputs:
      employee_name:
        description: "The name of the new employee"
        required: true
        type: string
      employee_email:
        description: "The email of the new employee"
        required: true
        type: string

jobs:
  create-onboarding-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Read onboarding checklist
        id: onboarding_checklist
        run: |
          CONTENT=$(cat employee-lifecycle/onboarding-checklist.md)
          CONTENT="**Employee Name:** ${{ github.event.inputs.employee_name }}\n**Employee Email:** ${{ github.event.inputs.employee_email }}\n\n$CONTENT"
          echo "content<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub issue for onboarding
        env:
          ISSUE_BODY: ${{ env.content }}
        run: |
          TEAM_MEMBERS=$(gh api orgs/yeatmanlab/teams/roar-infosec-maintainers/members --jq '.[].login')

          ISSUE_NUMBER=$(gh issue create --title "New Employee Onboarding Checklist for ${{ github.event.inputs.employee_name }}" --body "$ISSUE_BODY" --label onboarding)

          # Loop through each team member and assign them to the issue
          for MEMBER in $TEAM_MEMBERS
          do
            gh issue assign $ISSUE_NUMBER --assignee $MEMBER
          done
