name: Request Employee Acknowledgment

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'  # Runs at midnight on January 1st and July 1st every year
  workflow_dispatch:   # This enables manual triggering


jobs:
  create-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Read issue body
        id: acknowledgment_request
        run: |
          CONTENT=$(cat .github/workflows/acknowledgment-request-template.md)
          echo "content<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create issue
        env:
          ISSUE_BODY: ${{ env.content }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue create --title "Create Acknowledgement Requests" --body "$ISSUE_BODY" --assignee richford

